#!/bin/bash
DEFAULT_VERSION="v1.11.3"
CLIENTS_PATH="$HOME/.kubectl"
DEFAULT_CLIENT="$CLIENTS_PATH/$DEFAULT_VERSION"

function downloadClient {
	mkdir -p "$CLIENTS_PATH"
	wget -O "$CLIENTS_PATH/$1" "https://storage.googleapis.com/kubernetes-release/release/$1/bin/linux/amd64/kubectl"
	chmod +x "$CLIENTS_PATH/$1"
}

#Download default client if we dont have it. To be able to ask the server for its version
if [ ! -f "$DEFAULT_CLIENT" ]; then
	downloadClient "$DEFAULT_VERSION"
fi

SERVER_VERSION=$($DEFAULT_CLIENT version -o json | jq ".serverVersion.gitVersion" -r | grep -Po "v\d+.\d+.\d+")
CLIENT="$CLIENTS_PATH/$SERVER_VERSION"

#Download client if we dont have it
if [ ! -f "$CLIENT" ]; then
	downloadClient "$SERVER_VERSION"
fi

$CLIENT "$@"
exit $?
