#!/bin/bash
DEFAULT_VERSION="v1.11.3"
CLIENTS_PATH="$HOME/.kubectl"
DEFAULT_CLIENT="$CLIENTS_PATH/$DEFAULT_VERSION"

function downloadClient {
	mkdir -p "$CLIENTS_PATH"
	wget -O "$CLIENTS_PATH/$1" "https://storage.googleapis.com/kubernetes-release/release/$1/bin/linux/amd64/kubectl"
	chmod +x "$CLIENTS_PATH/$1"
}

if ! [ -x "$(command -v jq)" ]; then
  echo 'Error: jq is not installed. Install it with your favorite package manager' >&2
  exit 1
fi

#Download default client if we dont have it. To be able to ask the server for its version
if [ ! -f "$DEFAULT_CLIENT" ]; then
	downloadClient "$DEFAULT_VERSION"
fi

VERSION_OUTPUT=$($DEFAULT_CLIENT version -o json 2>&1)
if grep -q "Unable to connect to the server" <<<"$VERSION_OUTPUT"; then
  # Echo as comment to make sure "kubectl completion" etc works in profile
  echo -e "#WARNING: Wrapper unable to verify server version, using default version $DEFAULT_VERSION.\n"
  $DEFAULT_CLIENT "$@"
else
  $SERVER_VERSION=$(echo $VERSION_OUTPUT | jq ".serverVersion.gitVersion" -r | grep -Po "v\d+.\d+.\d+")
  CLIENT="$CLIENTS_PATH/$SERVER_VERSION"
  #Download client if we dont have it
  if [ ! -f "$CLIENT" ]; then
        downloadClient "$SERVER_VERSION"
  fi
  $CLIENT "$@"
fi

exit $?
